/* Generated By:JavaCC: Do not edit this line. SASplusParserTokenManager.java */
package sas.parser;
import sas.data.*;
import sas.data.SASAxiom.SASPair;
import sas.util.CausalGraphLink;
import javaff.graph.*;
import java.io.PrintStream;
import java.io.File;
import java.io.FileReader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.Hashtable;
import java.util.Set;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map.Entry;
import java.util.StringTokenizer;
import java.math.BigDecimal;

/** Token Manager. */
public class SASplusParserTokenManager implements SASplusParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x2fffff80L) != 0L)
         {
            jjmatchedKind = 33;
            return 19;
         }
         return -1;
      case 1:
         if ((active0 & 0x2fffff80L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 1;
            return 19;
         }
         return -1;
      case 2:
         if ((active0 & 0x2fffff80L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 2;
            return 19;
         }
         return -1;
      case 3:
         if ((active0 & 0xfffff80L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 3;
            return 19;
         }
         if ((active0 & 0x20000000L) != 0L)
            return 19;
         return -1;
      case 4:
         if ((active0 & 0x7ffff80L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 4;
            return 19;
         }
         if ((active0 & 0x8000000L) != 0L)
            return 19;
         return -1;
      case 5:
         if ((active0 & 0x3bfff80L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 5;
            return 19;
         }
         if ((active0 & 0x4400000L) != 0L)
            return 19;
         return -1;
      case 6:
         if ((active0 & 0x2bfff80L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 6;
            return 19;
         }
         if ((active0 & 0x1000000L) != 0L)
            return 19;
         return -1;
      case 7:
         if ((active0 & 0x8ffe80L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 7;
            return 19;
         }
         if ((active0 & 0x2300100L) != 0L)
            return 19;
         return -1;
      case 8:
         if ((active0 & 0xfee80L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 8;
            return 19;
         }
         if ((active0 & 0x801000L) != 0L)
            return 19;
         return -1;
      case 9:
         if ((active0 & 0x6ea00L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 9;
            return 19;
         }
         if ((active0 & 0x90480L) != 0L)
            return 19;
         return -1;
      case 10:
         if ((active0 & 0x6e200L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 10;
            return 19;
         }
         if ((active0 & 0x800L) != 0L)
            return 19;
         return -1;
      case 11:
         if ((active0 & 0x62000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 11;
            return 19;
         }
         if ((active0 & 0xc200L) != 0L)
            return 19;
         return -1;
      case 12:
         if ((active0 & 0x22000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 12;
            return 19;
         }
         if ((active0 & 0x40000L) != 0L)
            return 19;
         return -1;
      case 13:
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 13;
            return 19;
         }
         if ((active0 & 0x2000L) != 0L)
            return 19;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 40:
         return jjStopAtPos(0, 5);
      case 41:
         return jjStopAtPos(0, 6);
      case 60:
         return jjMoveStringLiteralDfa1_0(0x40000000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x20000000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x2aaaa80L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x5555500L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa1_0(0x8000000L);
      default :
         return jjMoveNfa_0(13, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x2aaaa80L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x45555500L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x5555500L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x2aaaa80L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x68000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa4_0(active0, 0x5555500L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x2aaaa80L);
      case 77:
      case 109:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(3, 29, 19);
         break;
      case 78:
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x10100L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x400L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x2aaaa80L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L);
      case 80:
      case 112:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 27, 19);
         break;
      case 82:
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa5_0(active0, 0x401000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000L);
      case 95:
         return jjMoveStringLiteralDfa6_0(active0, 0x2aaaa80L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa6_0(active0, 0x400L);
      case 71:
      case 103:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(5, 22, 19);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(5, 26, 19);
         break;
      case 79:
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x100L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x1001000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x1100L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000L);
      case 71:
      case 103:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(6, 24, 19);
         return jjMoveStringLiteralDfa7_0(active0, 0x8080L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x200L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x40012000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0xc0000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa7_0(active0, 0x200800L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x400L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000L);
      case 69:
      case 101:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(7, 20, 19);
         return jjMoveStringLiteralDfa8_0(active0, 0x200L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000L);
      case 71:
      case 103:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(7, 21, 19);
         else if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(7, 25, 19);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000L);
      case 76:
      case 108:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(7, 8, 19);
         break;
      case 79:
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0x80L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0xc400L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x801800L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa8_0(active0, 0x90000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa9_0(active0, 0x40000000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x44880L);
      case 69:
      case 101:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(8, 12, 19);
         return jjMoveStringLiteralDfa9_0(active0, 0x2000L);
      case 71:
      case 103:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(8, 23, 19);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x400L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0x200L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 66:
      case 98:
         return jjMoveStringLiteralDfa10_0(active0, 0x40000L);
      case 67:
      case 99:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(9, 10, 19);
         break;
      case 69:
      case 101:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(9, 19, 19);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000L);
      case 76:
      case 108:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(9, 7, 19);
         break;
      case 82:
      case 114:
         return jjMoveStringLiteralDfa10_0(active0, 0x2200L);
      case 83:
      case 115:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(9, 16, 19);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa10_0(active0, 0x40004800L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa10_0(active0, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa11_0(active0, 0x22000L);
      case 69:
      case 101:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(10, 11, 19);
         break;
      case 72:
      case 104:
         return jjMoveStringLiteralDfa11_0(active0, 0x40000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa11_0(active0, 0x200L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa11_0(active0, 0x40000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa11_0(active0, 0x4000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa11_0(active0, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 66:
      case 98:
         return jjMoveStringLiteralDfa12_0(active0, 0x20000L);
      case 67:
      case 99:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(11, 9, 19);
         break;
      case 69:
      case 101:
         return jjMoveStringLiteralDfa12_0(active0, 0x40000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa12_0(active0, 0x40000000L);
      case 82:
      case 114:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(11, 14, 19);
         break;
      case 83:
      case 115:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(11, 15, 19);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa12_0(active0, 0x2000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 76:
      case 108:
         return jjMoveStringLiteralDfa13_0(active0, 0x20000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa13_0(active0, 0x2000L);
      case 83:
      case 115:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(12, 18, 19);
         return jjMoveStringLiteralDfa13_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa14_0(active0, 0x40020000L);
      case 82:
      case 114:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(13, 13, 19);
         break;
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x40000000L) != 0L)
            return jjStopAtPos(14, 30);
         break;
      case 83:
      case 115:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(14, 17, 19);
         break;
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 25;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 13:
                  if ((0x3ff200000000000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(19);
                  }
                  else if ((0x400100000000000L & l) != 0L)
                  {
                     if (kind > 31)
                        kind = 31;
                  }
                  else if (curChar == 59)
                     jjCheckNAddStates(0, 3);
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 32)
                        kind = 32;
                     jjCheckNAddTwoStates(16, 17);
                  }
                  else if (curChar == 45)
                     jjCheckNAdd(16);
                  break;
               case 1:
                  if (curChar == 45)
                     jjCheckNAdd(2);
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddTwoStates(2, 3);
                  break;
               case 3:
                  if (curChar == 46)
                     jjCheckNAdd(4);
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAdd(4);
                  break;
               case 10:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 14:
                  if ((0x400100000000000L & l) != 0L && kind > 31)
                     kind = 31;
                  break;
               case 15:
                  if (curChar == 45)
                     jjCheckNAdd(16);
                  break;
               case 16:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 32)
                     kind = 32;
                  jjCheckNAddTwoStates(16, 17);
                  break;
               case 17:
                  if (curChar == 46)
                     jjCheckNAdd(18);
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 32)
                     kind = 32;
                  jjCheckNAdd(18);
                  break;
               case 19:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(19);
                  break;
               case 20:
                  if (curChar == 59)
                     jjCheckNAddStates(0, 3);
                  break;
               case 21:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 22:
                  if ((0x2400L & l) != 0L && kind > 34)
                     kind = 34;
                  break;
               case 23:
                  if (curChar == 10 && kind > 34)
                     kind = 34;
                  break;
               case 24:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 13:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(19);
                  }
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 0:
                  if (curChar == 64)
                     jjAddStates(7, 8);
                  break;
               case 5:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 6:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 7:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if ((0x100000001000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 11:
                  if ((0x80000000800000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 19:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(19);
                  break;
               case 21:
                  jjAddStates(4, 6);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 21:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(4, 6);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 25 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   20, 21, 22, 24, 21, 22, 24, 1, 2, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\50", "\51", null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x3ffffffe1L, 
};
static final long[] jjtoSkip = {
   0x40000001eL, 
};
static final long[] jjtoSpecial = {
   0x400000000L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[25];
private final int[] jjstateSet = new int[50];
protected char curChar;
/** Constructor. */
public SASplusParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public SASplusParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 25; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         matchedToken.specialToken = specialToken;
         return matchedToken;
      }
      else
      {
         if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
         {
            matchedToken = jjFillToken();
            if (specialToken == null)
               specialToken = matchedToken;
            else
            {
               matchedToken.specialToken = specialToken;
               specialToken = (specialToken.next = matchedToken);
            }
         }
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
