/* Generated By:JavaCC: Do not edit this line. SASplusParserConstants.java */
package sas.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SASplusParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPEN = 5;
  /** RegularExpression Id. */
  int CLOSE = 6;
  /** RegularExpression Id. */
  int BEGIN_GOAL = 7;
  /** RegularExpression Id. */
  int END_GOAL = 8;
  /** RegularExpression Id. */
  int BEGIN_METRIC = 9;
  /** RegularExpression Id. */
  int END_METRIC = 10;
  /** RegularExpression Id. */
  int BEGIN_STATE = 11;
  /** RegularExpression Id. */
  int END_STATE = 12;
  /** RegularExpression Id. */
  int BEGIN_OPERATOR = 13;
  /** RegularExpression Id. */
  int END_OPERATOR = 14;
  /** RegularExpression Id. */
  int BEGIN_GROUPS = 15;
  /** RegularExpression Id. */
  int END_GROUPS = 16;
  /** RegularExpression Id. */
  int BEGIN_VARIABLES = 17;
  /** RegularExpression Id. */
  int END_VARIABLES = 18;
  /** RegularExpression Id. */
  int BEGIN_RULE = 19;
  /** RegularExpression Id. */
  int END_RULE = 20;
  /** RegularExpression Id. */
  int BEGIN_SG = 21;
  /** RegularExpression Id. */
  int END_SG = 22;
  /** RegularExpression Id. */
  int BEGIN_DTG = 23;
  /** RegularExpression Id. */
  int END_DTG = 24;
  /** RegularExpression Id. */
  int BEGIN_CG = 25;
  /** RegularExpression Id. */
  int END_CG = 26;
  /** RegularExpression Id. */
  int GROUP = 27;
  /** RegularExpression Id. */
  int NEW_AXIOM = 28;
  /** RegularExpression Id. */
  int ATOM = 29;
  /** RegularExpression Id. */
  int NONE_OF_THOSE = 30;
  /** RegularExpression Id. */
  int SEPARATOR = 31;
  /** RegularExpression Id. */
  int NUMBER = 32;
  /** RegularExpression Id. */
  int NAME = 33;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"begin_goal\"",
    "\"end_goal\"",
    "\"begin_metric\"",
    "\"end_metric\"",
    "\"begin_state\"",
    "\"end_state\"",
    "\"begin_operator\"",
    "\"end_operator\"",
    "\"begin_groups\"",
    "\"end_groups\"",
    "\"begin_variables\"",
    "\"end_variables\"",
    "\"begin_rule\"",
    "\"end_rule\"",
    "\"begin_SG\"",
    "\"end_SG\"",
    "\"begin_DTG\"",
    "\"end_DTG\"",
    "\"begin_CG\"",
    "\"end_CG\"",
    "\"group\"",
    "<NEW_AXIOM>",
    "\"ATOM\"",
    "\"<none of those>\"",
    "<SEPARATOR>",
    "<NUMBER>",
    "<NAME>",
    "<SINGLE_LINE_COMMENT>",
  };

}
